version: "3"

services:
  frontend:
    image: caddy:latest
    container_name: frontend
    volumes:
      - caddy_data:/data
      - dashboard_assets:/var/www/dashboard
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - builder
    ports:
      - 443:443
      - 80:80
  builder:
    build:
      dockerfile: "./Dockerfile"
      context: .
    container_name: build
    restart: "no"
    volumes:
      - './.git/:/source:ro'
      - dashboard_assets:/target
    environment:
      REV: bootstrap
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    volumes:
      - 'gitlab_config':/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  caddy_data:
  dashboard_assets:
